import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "DM Sans", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        serif: ["Playfair Display", "Cormorant Garamond", "Georgia", "serif"],
        display: ["Playfair Display", "Cormorant Garamond", "Georgia", "serif"],
      },
      fontSize: {
        "hero": ["clamp(2.5rem, 5vw + 2rem, 5rem)", { lineHeight: "1.15", letterSpacing: "-0.02em" }],
        "hero-sm": ["clamp(2.25rem, 4vw + 1.5rem, 4.5rem)", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "section": ["clamp(2rem, 3vw + 1.5rem, 3.5rem)", { lineHeight: "1.2", letterSpacing: "-0.015em" }],
        "subsection": ["clamp(1.5rem, 2vw + 1rem, 2.25rem)", { lineHeight: "1.25", letterSpacing: "-0.01em" }],
        "card-title": ["clamp(1.25rem, 1.5vw + 0.75rem, 1.75rem)", { lineHeight: "1.3" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75" }],
        "body": ["1rem", { lineHeight: "1.75" }],
        "small": ["0.875rem", { lineHeight: "1.6" }],
        "caption": ["0.8125rem", { lineHeight: "1.5" }],
      },
      fontWeight: {
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
      },
      lineHeight: {
        "heading": "1.25",
        "heading-tight": "1.15",
        "body": "1.75",
        "body-relaxed": "1.8",
        "tight-nums": "1",
      },
      letterSpacing: {
        "hero": "-0.02em",
        "heading": "-0.015em",
        "heading-tight": "-0.01em",
        "body": "0",
        "label": "0.12em",
        "label-wide": "0.2em",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        gold: {
          DEFAULT: "hsl(var(--gold))",
          light: "hsl(var(--gold-light))",
          dark: "hsl(var(--gold-dark))",
          50: "#FFF9E6",
          100: "#FFF3CC",
          200: "#FFE799",
          300: "#FFDB66",
          400: "#E5C048",
          500: "#D4AF37",
          600: "#C19B2E",
          700: "#A67C00",
          800: "#8A6600",
          900: "#6E5000",
        },
        champagne: "hsl(var(--champagne))",
        "rose-gold": "hsl(var(--rose-gold))",
        blush: "hsl(var(--blush))",
        ivory: "hsl(var(--ivory))",
        charcoal: "hsl(var(--charcoal))",
        navy: "hsl(var(--navy))",
        "off-white": "hsl(var(--off-white))",
        "medium-gray": "#666666",
        emerald: "hsl(var(--emerald))",
        espresso: {
          DEFAULT: "#3E2723",
          light: "#5D4037",
          dark: "#2D1F1D",
        },
        silk: "#F5F3EF",
        pearl: "#E8E6E3",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        sparkle: {
          "0%, 100%": { opacity: "0", transform: "scale(0) rotate(0deg)" },
          "50%": { opacity: "1", transform: "scale(1) rotate(180deg)" },
        },
        "scroll-indicator": {
          "0%, 100%": { transform: "translateY(0)", opacity: "1" },
          "50%": { transform: "translateY(10px)", opacity: "0.5" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        glow: {
          "0%, 100%": { boxShadow: "0 0 20px hsl(var(--gold) / 0.3)" },
          "50%": { boxShadow: "0 0 40px hsl(var(--gold) / 0.6)" },
        },
        "polaroid-scroll-left": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "polaroid-scroll-right": {
          "0%": { transform: "translateX(-50%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out forwards",
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        "scale-in": "scale-in 0.5s ease-out forwards",
        shimmer: "shimmer 2s linear infinite",
        float: "float 6s ease-in-out infinite",
        pulse: "pulse 2s ease-in-out infinite",
        sparkle: "sparkle 3s ease-in-out infinite",
        "scroll-indicator": "scroll-indicator 2s ease-in-out infinite",
        "slide-in-left": "slide-in-left 0.6s ease-out forwards",
        "slide-in-right": "slide-in-right 0.6s ease-out forwards",
        glow: "glow 2s ease-in-out infinite",
        "polaroid-scroll-left": "polaroid-scroll-left 45s linear infinite",
        "polaroid-scroll-right": "polaroid-scroll-right 50s linear infinite",
      },
      backgroundImage: {
        "gradient-gold": "var(--gradient-gold)",
        "gradient-rose": "var(--gradient-rose)",
        "gradient-hero": "var(--gradient-hero)",
        "gradient-hero-overlay": "var(--gradient-hero-overlay)",
        "gradient-champagne": "linear-gradient(135deg, #FFFBF5 0%, #FFF8F0 50%, #FFF4E6 100%)",
        "gradient-rose-heritage": "linear-gradient(135deg, #FFF0F5 0%, #FFE4E8 100%)",
        "gradient-parchment": "linear-gradient(135deg, #FFF8DC 0%, #FFEAA7 100%)",
      },
      boxShadow: {
        glass: "var(--glass-shadow)",
        luxury: "0 25px 50px -12px rgba(212, 175, 55, 0.2)",
        "luxury-lg": "0 35px 60px -15px rgba(212, 175, 55, 0.25)",
        "heritage-sm": "0 2px 8px rgba(62, 39, 35, 0.04)",
        "heritage-md": "0 4px 16px rgba(62, 39, 35, 0.06)",
        "heritage-lg": "0 8px 32px rgba(62, 39, 35, 0.08)",
        "heritage-xl": "0 12px 48px rgba(62, 39, 35, 0.10)",
        "gold-glow": "0 8px 24px rgba(212, 175, 55, 0.30)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
